# Generated by Django 3.2.20 on 2024-06-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insial', models.CharField(max_length=1)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1)),
                ('usia', models.IntegerField()),
                ('partai_nasional', models.CharField(max_length=120)),
                ('partai_daerah', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('durasi', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
