# Generated by Django 3.2.20 on 2024-06-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='insial',
            new_name='inisial',
        ),
    ]
