# Generated by Django 3.2.20 on 2024-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20240622_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='inisial',
            field=models.CharField(max_length=120),
        ),
    ]
