# Generated by Django 3.2.20 on 2024-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_alter_participant_inisial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_question_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
