# Generated by Django 3.2.20 on 2024-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_participant_participant_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='prioritas_kategori',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
