# Generated by Django 3.2.20 on 2024-07-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quistionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('likert', 'LIKERT'), ('text', 'TEXT')], max_length=12)),
                ('scale', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
