# Generated by Django 3.2.20 on 2024-06-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='candidate',
            new_name='kandidat',
        ),
    ]
