# Generated by Django 3.2.20 on 2024-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_rename_candidate_information_kandidat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoNextSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLimitSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=15)),
            ],
        ),
    ]
