# Generated by Django 3.2.20 on 2024-06-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20240622_1719'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inisial', models.CharField(max_length=120)),
                ('kandidat', models.CharField(max_length=120)),
                ('partai', models.CharField(max_length=120)),
                ('kategori', models.CharField(max_length=120)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
        migrations.CreateModel(
            name='RecordProporsional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inisial', models.CharField(max_length=120)),
                ('kandidat', models.CharField(max_length=120)),
                ('partai', models.CharField(max_length=120)),
                ('kategori', models.CharField(max_length=120)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
