# Generated by Django 3.2.20 on 2024-06-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20240622_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddistrict',
            name='durasi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordproporsional',
            name='durasi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordsimulation',
            name='durasi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
