# Generated by Django 3.2.20 on 2024-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20240623_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationCategoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=120)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
