# Generated by Django 3.2.20 on 2024-07-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_participant_participant_question_answer'),
        ('record', '0004_durationcategoryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='durationcategoryrecord',
            name='iniisial',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='durationcategoryrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant'),
        ),
    ]
