# Generated by Django 3.2.20 on 2024-07-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20240722_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='durationcategoryrecord',
            old_name='iniisial',
            new_name='inisial',
        ),
        migrations.RenameField(
            model_name='durationcategoryrecord',
            old_name='user',
            new_name='participant',
        ),
    ]
